name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Ubuntu-coverage:
    runs-on: ubuntu-24.04
    
    env:
      FC: gfortran
      PFUNIT_DIR: /home/runner/work/GORILLA/GORILLA/pFUnit/build/installed/PFUNIT-4.7/

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gfortran liblapack-dev libnetcdff-dev
          sudo apt install lcov

      - name: Install pFUnit
        run: |
          git clone --branch v4.7.0 https://github.com/Goddard-Fortran-Ecosystem/pFUnit
          cd pFUnit
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
          make tests
          make install

      - name: Build
        run: |
          ./build_coverage.sh
        
      - name: Archive code coverage results
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-report
          path: BUILD/COVERAGE/
          
  Ubuntu:
    runs-on: ubuntu-24.04
    
    env:
      FC: gfortran
      PFUNIT_DIR: /home/runner/work/GORILLA/GORILLA/pFUnit/build/installed/PFUNIT-4.7

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gfortran liblapack-dev libnetcdff-dev

      - name: Build
        run: |
          make
          
      - name: Run examples
        run: |
          for i in 1 2 3 4 5 6 7; do
            (cd EXAMPLES/example_$i && ./test_gorilla_main.x)
          done
          
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        
      - name: Run MATLAB scripts
        uses: matlab-actions/run-command@v3
        with:
          command: |
            cd MATLAB
            example_1
            example_2
            example_3
            example_4
            example_5
            example_6
            example_7
            example_8

      - name: Run MATLAB livescript
        uses: matlab-actions/run-command@v3
        with:
          command: |
            cd MATLAB
            plotting_tutorial

      - name: Archive MATLAB results
        uses: actions/upload-artifact@v7
        with:
          name: MATLAB-RESULTS
          path: MATLAB/data_plots
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install PYTHON dependencies
        run: |
          python -m pip install --upgrade pip
          pip install f90nml numpy matplotlib jupyter jupyterlab
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run PYTHON scripts
        run: |
          cd PYTHON
          python3 example_1.py
          python3 example_2.py
          python3 example_3.py
          python3 example_4.py
          python3 example_5.py
          python3 example_6.py
          python3 example_7.py

      - name: Run PYTHON plottingscripts
        run: |
          cd PYTHON
          python3 plot_example_1.py
          python3 plot_example_2.py
          python3 plot_example_3.py
          python3 plot_example_4.py
          python3 plot_example_5.py
          python3 plot_example_6.py
          python3 plot_example_7.py

      - name: Run JUPYTER notebook
        run: |
          cd PYTHON
          jupyter nbconvert --to script plotting_tutorial.ipynb
          python3 plotting_tutorial.py

      - name: Archive PYTHON results
        uses: actions/upload-artifact@v7
        with:
          name: PYTHON-RESULTS
          path: PYTHON/data_plots

          
